service Calculadora {
    void ping (),
    double suma(1: double num1, 2: double num2 ),
    double resta(1: double num1, 2: double num2 ),
    double multiplicacion (1: double num1, 2: double num2),
    double division(1: double num1, 2: double num2),
    double potencia(1: double base, 2: double exponente),
    double logaritmo(1: double base, 2: double num),
    double raiz(1: double base, 2: double exponente),
    double seno(1: double num1),
    double coseno(1: double num1),
    double tangente(1: double num1),
    double conversion(1: double num1, 2: string strn),

    list<double> suma_vectores(1: list<double> vect1, 2:list<double> vect2), 
    list<double> resta_vectores(1: list<double> vect1, 2:list<double> vect2), 
    double producto_escalar(1: list<double> vect1, 2: list<double> vect2),
    list<double> producto_vectorial(1: list<double> vect1, 2:list<double> vect2),
	double norma (1: list<double> vect1),
	double angulo_vectores (1: list<double> vect1, 2: list<double> vect2),
    double producto_mixto(1: list<double> vect1 ,2: list<double> vect2, 3: list<double> vect3),

    list<list<double>> suma_matrices(1: list<list<double>> m1, 2:list<list<double>> m2), 
    list<list<double>> resta_matrices(1: list<list<double>> m1, 2:list<list<double>> m2), 
    list<list<double>> producto_matrices(1: list<list<double>> m1, 2:list<list<double>> m2), 
    double determinante(1: list<list<double>> m1), 
    list<list<double>> inversa(1: list<list<double>> m1), 
}
