/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "calculadora.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

resultado *
suma_1(double arg1, double arg2,  CLIENT *clnt)
{
	suma_1_argument arg;
	static resultado clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, suma, (xdrproc_t) xdr_suma_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_resultado, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

resultado *
resta_1(double arg1, double arg2,  CLIENT *clnt)
{
	resta_1_argument arg;
	static resultado clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, resta, (xdrproc_t) xdr_resta_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_resultado, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

resultado *
multiplicacion_1(double arg1, double arg2,  CLIENT *clnt)
{
	multiplicacion_1_argument arg;
	static resultado clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, multiplicacion, (xdrproc_t) xdr_multiplicacion_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_resultado, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

resultado *
division_1(double arg1, double arg2,  CLIENT *clnt)
{
	division_1_argument arg;
	static resultado clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, division, (xdrproc_t) xdr_division_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_resultado, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

resultado *
potencia_1(double arg1, double arg2,  CLIENT *clnt)
{
	potencia_1_argument arg;
	static resultado clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, potencia, (xdrproc_t) xdr_potencia_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_resultado, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

resultado *
logaritmo_1(double arg1, double arg2,  CLIENT *clnt)
{
	logaritmo_1_argument arg;
	static resultado clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, logaritmo, (xdrproc_t) xdr_logaritmo_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_resultado, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

resultado *
raiz_1(double arg1, double arg2,  CLIENT *clnt)
{
	raiz_1_argument arg;
	static resultado clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, raiz, (xdrproc_t) xdr_raiz_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_resultado, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

vect *
suma_vectores_2(vect arg1, vect arg2,  CLIENT *clnt)
{
	suma_vectores_2_argument arg;
	static vect clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, suma_vectores, (xdrproc_t) xdr_suma_vectores_2_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_vect, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

vect *
resta_vectores_2(vect arg1, vect arg2,  CLIENT *clnt)
{
	resta_vectores_2_argument arg;
	static vect clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, resta_vectores, (xdrproc_t) xdr_resta_vectores_2_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_vect, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

resultado *
producto_escalar_2(vect arg1, vect arg2,  CLIENT *clnt)
{
	producto_escalar_2_argument arg;
	static resultado clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, producto_escalar, (xdrproc_t) xdr_producto_escalar_2_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_resultado, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

vect *
producto_vectorial_2(vect arg1, vect arg2,  CLIENT *clnt)
{
	producto_vectorial_2_argument arg;
	static vect clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, producto_vectorial, (xdrproc_t) xdr_producto_vectorial_2_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_vect, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

resultado *
norma_2(vect arg1,  CLIENT *clnt)
{
	static resultado clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, norma,
		(xdrproc_t) xdr_vect, (caddr_t) &arg1,
		(xdrproc_t) xdr_resultado, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

resultado *
angulo_vectores_2(vect arg1, vect arg2,  CLIENT *clnt)
{
	angulo_vectores_2_argument arg;
	static resultado clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, angulo_vectores, (xdrproc_t) xdr_angulo_vectores_2_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_resultado, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

vect *
comp_ortogonales_2(vect arg1, vect arg2,  CLIENT *clnt)
{
	comp_ortogonales_2_argument arg;
	static vect clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, comp_ortogonales, (xdrproc_t) xdr_comp_ortogonales_2_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_vect, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

resultado *
producto_mixto_2(vect arg1, vect arg2, vect arg3,  CLIENT *clnt)
{
	producto_mixto_2_argument arg;
	static resultado clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	if (clnt_call (clnt, producto_mixto, (xdrproc_t) xdr_producto_mixto_2_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_resultado, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
