/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

// Función para imprimir un vector por pantalla
void imprimir_vector(vect v, unsigned int num_vector) {
    if (v.vect_len == 0) {
        printf("Vector %d: El vector está vacío o es nulo.\n", num_vector);
        return;
    } else {
		printf("Vector %d de longitud %u: (", num_vector, v.vect_len);
    	for (unsigned int i = 0; i < v.vect_len; i++) {
			printf("%.2f", v.vect_val[i]);
			if (i < v.vect_len - 1) printf(", ");
		}
		printf(")\n");
	}
}

void
calculadora_1(char *host, double n1, char op, double n2) {
	CLIENT *clnt;
	resultado  *solucion;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA, CALCULADORA_BASICA, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	switch (op) {
	case '+':
		solucion = suma_1(n1, n2, clnt);
		if (solucion == (resultado *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		printf("La operacion suma: %lf + %lf = %lf\n", n1, n2, solucion->resultado_u.resultado);
		break;
	
	case '-':
		solucion = resta_1(n1, n2, clnt);
		if (solucion == (resultado *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		printf("La operacion resta: %lf - %lf = %lf\n", n1, n2, solucion->resultado_u.resultado);
		break;

	case '*':
		solucion = multiplicacion_1(n1, n2, clnt);
		if (solucion == (resultado *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		printf("La operacion multiplicacion: %lf * %lf = %lf\n", n1, n2, solucion->resultado_u.resultado);	
		break;

	case '/':
		solucion = division_1(n1, n2, clnt);
		if (solucion == (resultado *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		printf("La operacion division: %lf / %lf = %lf\n", n1, n2, solucion->resultado_u.resultado);
		break;

	case '^':
		solucion = potencia_1(n1, n2, clnt);
		if (solucion == (resultado *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		printf("La operacion potencia: %lf ^ %lf = %lf\n", n1, n2, solucion->resultado_u.resultado);
		break;
	
	case 'l':
		solucion = logaritmo_1(n1, n2, clnt);
		if (solucion == (resultado *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		printf("La operacion logaritmo: log %lf ( %lf ) = %lf\n", n1, n2, solucion->resultado_u.resultado);
		break;

	case 'r':
		solucion = raiz_1(n1, n2, clnt);
		if (solucion == (resultado *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		printf("La operacion raiz: %lf √ %lf = %lf\n", n2, n1, solucion->resultado_u.resultado);
		break;
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
calculadora_2(char *host, vect v1, vect v2, vect v3, char op)
{
	CLIENT *clnt;
	vect  *resultado_v;
	resultado  *solucion;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA, CALCULADORA_vect, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	switch (op) {
	case '+':
		if( 0 < v1.vect_len && 0 < v2.vect_len ){
			resultado_v = suma_vectores_2(v1, v2, clnt);
			if (resultado_v == (vect *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			printf("Solución: ");
			imprimir_vector(*resultado_v, 4);
		} else {
			printf("La dimensión de ambos vectores debe de ser mayor a 0");
		}
		break;
	
	case '-':
		if( 0 < v1.vect_len && 0 < v2.vect_len ){
			resultado_v = resta_vectores_2(v1, v2, clnt);
			if (resultado_v == (vect *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			printf("Solución: ");
			imprimir_vector(*resultado_v,4);		
		} else {
			printf("La dimensión de ambos vectores debe de ser mayor a 0");
		}
		break;

	case '.':
		if( 0 < v1.vect_len && 0 < v2.vect_len ){
			solucion = producto_escalar_2(v1, v2, clnt);
			if (solucion == (resultado *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			printf("El producto escalar es: %lf \n", solucion->resultado_u.resultado);
		} else {
			printf("La dimensión de ambos vectores debe de ser mayor a 0");
		}
		break;

	case 'x':
		if( 0 < v1.vect_len <= 3 && 0 < v2.vect_len <= 3 ){
			resultado_v = producto_vectorial_2(v1, v2, clnt);
			if (resultado_v == (vect *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			printf("El producto vectorial es: ");
			imprimir_vector(*resultado_v,4);
		} else {
			printf("La dimensión de ambos vectores debe de ser menor a 4");
		}
				
		break;

	case 'n':
		if( 0 < v1.vect_len ){
			solucion = norma_2(v1, clnt);
			if (solucion == (resultado *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			printf("La norma es: %lf \n", solucion->resultado_u.resultado);
		} else {
			printf("La dimensión de ambos vectores debe de ser mayor a 0");
		}
		break;

	case 'a':
		if( 0 < v1.vect_len && 0 < v2.vect_len ){
			solucion = angulo_vectores_2(v1, v2, clnt);
			if (solucion == (resultado *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			printf("El angulo que forman los vectores es: %lf \n", solucion->resultado_u.resultado);	
		} else {
			printf("La dimensión de ambos vectores debe de ser mayor a 0");
		}
		break;
	
	case 'c':
		if( 0 < v1.vect_len && 0 < v2.vect_len ){
			resultado_v = comp_ortogonales_2(v1, v2, clnt);
			if (resultado_v == (vect *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			printf("Componentes ortogonales: ");
			imprimir_vector(*resultado_v,4);	
		} else {
			printf("La dimensión de ambos vectores debe de ser mayor a 0");
		}	
		break;

	case 'm':
		if( 0 < v1.vect_len <= 3 && 0 < v2.vect_len <= 3 && 0 < v3.vect_len <= 3 ){
			solucion = producto_mixto_2(v1, v2, v3, clnt);
			if (solucion == (resultado *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			printf("El producto mixto es: %lf \n", solucion->resultado_u.resultado);		
		} else {
			printf("La dimensión de ambos vectores debe de ser menor a 4");
		}
		break;
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

// Función para crear un vector con una longitud dada
vect crear_vector(unsigned int longitud) {
    vect v;
    v.vect_len = longitud;
    v.vect_val = (double *)malloc(longitud * sizeof(double));
    if (v.vect_val == NULL) {
        fprintf(stderr, "Error: No se pudo asignar memoria para el vector.\n");
        exit(1);
    }
    return v;
}

// Función para liberar la memoria asignada a un vector
void liberar_vector(vect v) {
    free(v.vect_val);
	v.vect_len = 0;
}


// Función para leer un vector desde la entrada estándar
vect leer_vector() {
    unsigned int longitud;
    printf("Ingrese la longitud del vector: ");
    scanf("%u", &longitud);
    vect v = crear_vector(longitud);
    printf("Ingrese los valores del vector separados por espacios: ");
    for (unsigned int i = 0; i < v.vect_len; i++) {
        scanf("%lf", &(v.vect_val[i]));
    }

    return v;
}

int
main (int argc, char *argv[]) {
	char *host;
	double n1, n2;
	int i1 = 1, i2 = 1, i3 = 1;
	vect v1, v2, v3;
	v1.vect_len = v2.vect_len = v3.vect_len = 0; //Inicialmente vacios
	char op = ' ';

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	while(TRUE) {
		printf("Selecione un modo: \n");
		printf(" 1 : Para calculadora básica\n");
		printf(" 2 : Para calculadora de vectores\n");
		printf(" e : Para salir (exit)\n");

		scanf(" %c", &op);
		if(op == 'e')
			break;

		switch (op) {
		case '1':
			while(TRUE) {
				printf("Selecione una operación: \n");
				printf(" + : Para una suma\n");
				printf(" - : Para una resta\n");
				printf(" * : Para una multiplicacion\n");
				printf(" / : Para una division\n");
				printf(" ^ : Para una potencia\n");
				printf(" l : Para un logaritmo\n");
				printf(" r : Para una raiz de exponente x\n");
				printf(" o : Para salir\n");

				scanf(" %c", &op);
				if(op == 'o')
					break;

				switch (op) {
				case '+': case '-': case '*': case '/':
					printf("Introduzca el primer numero: ");
					scanf("%lf", &n1);
					
					printf("Introduzca el segundo numero: ");
					scanf("%lf", &n2);

					if(op == '/')
						while(n2 == 0){
							printf("Error. Introduzca un divisor distinto de cero\n");
							scanf("%lf", &n2);
						}
					
					break;
				
				case '^': case 'r':
					printf("Introduzca la base:");
					scanf("%lf", &n1);
					
					printf("Introduzca el exponente:");
					scanf("%lf", &n2);
					break;
				
				case 'l':
					printf("Introduzca la base\n");
					scanf("%lf", &n1);
					
					printf("Introduzca el numero\n");
					scanf("%lf", &n2);
					break;
				}
				
				calculadora_1 (host, n1, op, n2);

				printf("\n********************************************************** \n");
			}
			break;
		
		case '2':
			while(TRUE) {
				printf("Vectores actuales: \n");
				imprimir_vector(v1,1);
				imprimir_vector(v2,2);
				imprimir_vector(v3,3);
				printf("NO hacer operaciones con vectores vacios,\n o de distinta dimensión \n");
				
				printf("\nSelecione una operación: \n");
				printf(" q : Para modificar algún vector\n");
				printf(" + : Para una suma\n");
				printf(" - : Para una resta\n");
				printf(" . : Para producto escalar\n");
				printf(" x : Para producto vectorial (3 dimensiones) \n");
				printf(" n : Para norma\n");
				printf(" a : Para angulo entre vectores\n");
				printf(" c : Para componentes ortogonales de la proyección x sobre y\n");
				printf(" m : Para producto mixto (3 dimensiones)\n");
				printf(" o : Para salir\n");

				scanf(" %c", &op);
				if(op == 'o')
					break;

				switch (op) {
				case 'q':
					printf("Elige vector a sobreescribir (1, 2 o 3): ");
    				scanf("%d", &i1);
					switch (i1){
					case 1:
						if(v1.vect_len != 0)
							liberar_vector(v1);
						v1 = leer_vector();
						break;
					case 2:
						if(v2.vect_len != 0)
							liberar_vector(v2);
						v2 = leer_vector();
						break;
					case 3:
						if(v3.vect_len != 0)
							liberar_vector(v3);
						v3 = leer_vector();
						break;
					default:
						break;
					}

					break;
				case '+': case '-': case '.': case 'x': case 'a': case 'c':
					printf("Seleccione el primer vector (1, 2 o 3): ");
    				scanf("%d", &i1);					
					printf("Seleccione el segundo vector (1, 2 o 3): ");
					scanf("%d", &i2);
					break;
				
				case 'n':
					printf("Seleccione el vector (1, 2 o 3):\n");
    				scanf("%d", &i1);					
					break;
				
				case 'm':
					printf("Operación (1 x 2)·3\n");
					printf("Seleccione el primer vector (1, 2 o 3): ");
    				scanf("%d", &i1);					
			
					printf("Seleccione el segundo vector (1, 2 o 3): ");
					scanf("%d", &i2);

					printf("Seleccione el tercer vector (1, 2 o 3): ");
					scanf("%d", &i3);
					break;
				}
				
				switch (i1) {
				case 1:
					switch (i2) {
						case 1:
							switch (i3) {
								case 1: calculadora_2(host, v1, v1, v1, op); break;
								case 2: calculadora_2(host, v1, v1, v2, op); break;
								case 3: calculadora_2(host, v1, v1, v3, op); break;
							}
							break;
						case 2:
							switch (i3) {
								case 1: calculadora_2(host, v1, v2, v1, op); break;
								case 2: calculadora_2(host, v1, v2, v2, op); break;
								case 3: calculadora_2(host, v1, v2, v3, op); break;
							}
							break;
						case 3:
							switch (i3) {
								case 1: calculadora_2(host, v1, v3, v1, op); break;
								case 2: calculadora_2(host, v1, v3, v2, op); break;
								case 3: calculadora_2(host, v1, v3, v3, op); break;
							}
							break;
					}
					break;
				case 2:
					switch (i2) {
						case 1:
							switch (i3) {
								case 1: calculadora_2(host, v2, v1, v1, op); break;
								case 2: calculadora_2(host, v2, v1, v2, op); break;
								case 3: calculadora_2(host, v2, v1, v3, op); break;
							}
							break;
						case 2:
							switch (i3) {
								case 1: calculadora_2(host, v2, v2, v1, op); break;
								case 2: calculadora_2(host, v2, v2, v2, op); break;
								case 3: calculadora_2(host, v2, v2, v3, op); break;
							}
							break;
						case 3:
							switch (i3) {
								case 1: calculadora_2(host, v2, v3, v1, op); break;
								case 2: calculadora_2(host, v2, v3, v2, op); break;
								case 3: calculadora_2(host, v2, v3, v3, op); break;
							}
							break;
					}
					break;
				case 3:
					switch (i2) {
						case 1:
							switch (i3) {
								case 1: calculadora_2(host, v3, v1, v1, op); break;
								case 2: calculadora_2(host, v3, v1, v2, op); break;
								case 3: calculadora_2(host, v3, v1, v3, op); break;
							}
							break;
						case 2:
							switch (i3) {
								case 1: calculadora_2(host, v3, v2, v1, op); break;
								case 2: calculadora_2(host, v3, v2, v2, op); break;
								case 3: calculadora_2(host, v3, v2, v3, op); break;
							}
							break;
						case 3:
							switch (i3) {
								case 1: calculadora_2(host, v3, v3, v1, op); break;
								case 2: calculadora_2(host, v3, v3, v2, op); break;
								case 3: calculadora_2(host, v3, v3, v3, op); break;
							}
							break;
					}
					break;
				}
				printf("\n\n********************************************************** \n");
			}
			break;
		}
		printf("\n---------------------------------------------------------------\n");
	}

	if(v1.vect_len != 0)
		liberar_vector(v1);
	if(v2.vect_len != 0)
		liberar_vector(v2);
	if(v3.vect_len != 0)
		liberar_vector(v3);
		
	exit (0);
}