/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static resultado *
_suma_1 (suma_1_argument *argp, struct svc_req *rqstp)
{
	return (suma_1_svc(argp->arg1, argp->arg2, rqstp));
}

static resultado *
_resta_1 (resta_1_argument *argp, struct svc_req *rqstp)
{
	return (resta_1_svc(argp->arg1, argp->arg2, rqstp));
}

static resultado *
_multiplicacion_1 (multiplicacion_1_argument *argp, struct svc_req *rqstp)
{
	return (multiplicacion_1_svc(argp->arg1, argp->arg2, rqstp));
}

static resultado *
_division_1 (division_1_argument *argp, struct svc_req *rqstp)
{
	return (division_1_svc(argp->arg1, argp->arg2, rqstp));
}

static resultado *
_potencia_1 (potencia_1_argument *argp, struct svc_req *rqstp)
{
	return (potencia_1_svc(argp->arg1, argp->arg2, rqstp));
}

static resultado *
_logaritmo_1 (logaritmo_1_argument *argp, struct svc_req *rqstp)
{
	return (logaritmo_1_svc(argp->arg1, argp->arg2, rqstp));
}

static resultado *
_raiz_1 (raiz_1_argument *argp, struct svc_req *rqstp)
{
	return (raiz_1_svc(argp->arg1, argp->arg2, rqstp));
}

static vect *
_suma_vectores_2 (suma_vectores_2_argument *argp, struct svc_req *rqstp)
{
	return (suma_vectores_2_svc(argp->arg1, argp->arg2, rqstp));
}

static vect *
_resta_vectores_2 (resta_vectores_2_argument *argp, struct svc_req *rqstp)
{
	return (resta_vectores_2_svc(argp->arg1, argp->arg2, rqstp));
}

static resultado *
_producto_escalar_2 (producto_escalar_2_argument *argp, struct svc_req *rqstp)
{
	return (producto_escalar_2_svc(argp->arg1, argp->arg2, rqstp));
}

static vect *
_producto_vectorial_2 (producto_vectorial_2_argument *argp, struct svc_req *rqstp)
{
	return (producto_vectorial_2_svc(argp->arg1, argp->arg2, rqstp));
}

static resultado *
_norma_2 (vect  *argp, struct svc_req *rqstp)
{
	return (norma_2_svc(*argp, rqstp));
}

static resultado *
_angulo_vectores_2 (angulo_vectores_2_argument *argp, struct svc_req *rqstp)
{
	return (angulo_vectores_2_svc(argp->arg1, argp->arg2, rqstp));
}

static vect *
_comp_ortogonales_2 (comp_ortogonales_2_argument *argp, struct svc_req *rqstp)
{
	return (comp_ortogonales_2_svc(argp->arg1, argp->arg2, rqstp));
}

static resultado *
_producto_mixto_2 (producto_mixto_2_argument *argp, struct svc_req *rqstp)
{
	return (producto_mixto_2_svc(argp->arg1, argp->arg2, argp->arg3, rqstp));
}

static void
calculadora_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		suma_1_argument suma_1_arg;
		resta_1_argument resta_1_arg;
		multiplicacion_1_argument multiplicacion_1_arg;
		division_1_argument division_1_arg;
		potencia_1_argument potencia_1_arg;
		logaritmo_1_argument logaritmo_1_arg;
		raiz_1_argument raiz_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case suma:
		_xdr_argument = (xdrproc_t) xdr_suma_1_argument;
		_xdr_result = (xdrproc_t) xdr_resultado;
		local = (char *(*)(char *, struct svc_req *)) _suma_1;
		break;

	case resta:
		_xdr_argument = (xdrproc_t) xdr_resta_1_argument;
		_xdr_result = (xdrproc_t) xdr_resultado;
		local = (char *(*)(char *, struct svc_req *)) _resta_1;
		break;

	case multiplicacion:
		_xdr_argument = (xdrproc_t) xdr_multiplicacion_1_argument;
		_xdr_result = (xdrproc_t) xdr_resultado;
		local = (char *(*)(char *, struct svc_req *)) _multiplicacion_1;
		break;

	case division:
		_xdr_argument = (xdrproc_t) xdr_division_1_argument;
		_xdr_result = (xdrproc_t) xdr_resultado;
		local = (char *(*)(char *, struct svc_req *)) _division_1;
		break;

	case potencia:
		_xdr_argument = (xdrproc_t) xdr_potencia_1_argument;
		_xdr_result = (xdrproc_t) xdr_resultado;
		local = (char *(*)(char *, struct svc_req *)) _potencia_1;
		break;

	case logaritmo:
		_xdr_argument = (xdrproc_t) xdr_logaritmo_1_argument;
		_xdr_result = (xdrproc_t) xdr_resultado;
		local = (char *(*)(char *, struct svc_req *)) _logaritmo_1;
		break;

	case raiz:
		_xdr_argument = (xdrproc_t) xdr_raiz_1_argument;
		_xdr_result = (xdrproc_t) xdr_resultado;
		local = (char *(*)(char *, struct svc_req *)) _raiz_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
calculadora_2(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		suma_vectores_2_argument suma_vectores_2_arg;
		resta_vectores_2_argument resta_vectores_2_arg;
		producto_escalar_2_argument producto_escalar_2_arg;
		producto_vectorial_2_argument producto_vectorial_2_arg;
		vect norma_2_arg;
		angulo_vectores_2_argument angulo_vectores_2_arg;
		comp_ortogonales_2_argument comp_ortogonales_2_arg;
		producto_mixto_2_argument producto_mixto_2_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case suma_vectores:
		_xdr_argument = (xdrproc_t) xdr_suma_vectores_2_argument;
		_xdr_result = (xdrproc_t) xdr_vect;
		local = (char *(*)(char *, struct svc_req *)) _suma_vectores_2;
		break;

	case resta_vectores:
		_xdr_argument = (xdrproc_t) xdr_resta_vectores_2_argument;
		_xdr_result = (xdrproc_t) xdr_vect;
		local = (char *(*)(char *, struct svc_req *)) _resta_vectores_2;
		break;

	case producto_escalar:
		_xdr_argument = (xdrproc_t) xdr_producto_escalar_2_argument;
		_xdr_result = (xdrproc_t) xdr_resultado;
		local = (char *(*)(char *, struct svc_req *)) _producto_escalar_2;
		break;

	case producto_vectorial:
		_xdr_argument = (xdrproc_t) xdr_producto_vectorial_2_argument;
		_xdr_result = (xdrproc_t) xdr_vect;
		local = (char *(*)(char *, struct svc_req *)) _producto_vectorial_2;
		break;

	case norma:
		_xdr_argument = (xdrproc_t) xdr_vect;
		_xdr_result = (xdrproc_t) xdr_resultado;
		local = (char *(*)(char *, struct svc_req *)) _norma_2;
		break;

	case angulo_vectores:
		_xdr_argument = (xdrproc_t) xdr_angulo_vectores_2_argument;
		_xdr_result = (xdrproc_t) xdr_resultado;
		local = (char *(*)(char *, struct svc_req *)) _angulo_vectores_2;
		break;

	case comp_ortogonales:
		_xdr_argument = (xdrproc_t) xdr_comp_ortogonales_2_argument;
		_xdr_result = (xdrproc_t) xdr_vect;
		local = (char *(*)(char *, struct svc_req *)) _comp_ortogonales_2;
		break;

	case producto_mixto:
		_xdr_argument = (xdrproc_t) xdr_producto_mixto_2_argument;
		_xdr_result = (xdrproc_t) xdr_resultado;
		local = (char *(*)(char *, struct svc_req *)) _producto_mixto_2;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (CALCULADORA, CALCULADORA_BASICA);
	pmap_unset (CALCULADORA, CALCULADORA_vect);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA, CALCULADORA_BASICA, calculadora_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA, CALCULADORA_BASICA, udp).");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA, CALCULADORA_vect, calculadora_2, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA, CALCULADORA_vect, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA, CALCULADORA_BASICA, calculadora_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA, CALCULADORA_BASICA, tcp).");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA, CALCULADORA_vect, calculadora_2, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA, CALCULADORA_vect, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
