/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"

bool_t
xdr_resultado (XDR *xdrs, resultado *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->errno))
		 return FALSE;
	switch (objp->errno) {
	case 0:
		 if (!xdr_double (xdrs, &objp->resultado_u.resultado))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_vect (XDR *xdrs, vect *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->vect_val, (u_int *) &objp->vect_len, ~0,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_suma_1_argument (XDR *xdrs, suma_1_argument *objp)
{
	 if (!xdr_double (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_resta_1_argument (XDR *xdrs, resta_1_argument *objp)
{
	 if (!xdr_double (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_multiplicacion_1_argument (XDR *xdrs, multiplicacion_1_argument *objp)
{
	 if (!xdr_double (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_division_1_argument (XDR *xdrs, division_1_argument *objp)
{
	 if (!xdr_double (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_potencia_1_argument (XDR *xdrs, potencia_1_argument *objp)
{
	 if (!xdr_double (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_logaritmo_1_argument (XDR *xdrs, logaritmo_1_argument *objp)
{
	 if (!xdr_double (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_raiz_1_argument (XDR *xdrs, raiz_1_argument *objp)
{
	 if (!xdr_double (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_suma_vectores_2_argument (XDR *xdrs, suma_vectores_2_argument *objp)
{
	 if (!xdr_vect (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_vect (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_resta_vectores_2_argument (XDR *xdrs, resta_vectores_2_argument *objp)
{
	 if (!xdr_vect (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_vect (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_producto_escalar_2_argument (XDR *xdrs, producto_escalar_2_argument *objp)
{
	 if (!xdr_vect (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_vect (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_producto_vectorial_2_argument (XDR *xdrs, producto_vectorial_2_argument *objp)
{
	 if (!xdr_vect (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_vect (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_angulo_vectores_2_argument (XDR *xdrs, angulo_vectores_2_argument *objp)
{
	 if (!xdr_vect (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_vect (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_comp_ortogonales_2_argument (XDR *xdrs, comp_ortogonales_2_argument *objp)
{
	 if (!xdr_vect (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_vect (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_producto_mixto_2_argument (XDR *xdrs, producto_mixto_2_argument *objp)
{
	 if (!xdr_vect (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_vect (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_vect (xdrs, &objp->arg3))
		 return FALSE;
	return TRUE;
}
